### ISSUE TITLE
关于在win10下编译pyflink

### ISSUE THREAD

**Issue by ShydowLi** [HuangXingBo/pyflink-demo#2]
您好，请问怎么在win10下编译pyflink

**Comment by HuangXingBo** [comment]
你先mvn clean install -DskipTests一下整个flink项目，

**Comment by HuangXingBo** [comment]
然后到flink-python目录下去python3 setup.py sdist或者python3 setup.py bdist_wheel。

**Comment by HuangXingBo** [comment]
然后去pip3 install dist/*.tar.gz就行

**Comment by ShydowLi** [comment]
嗯嗯，谢谢啊，成功安装了，但在windows下不能使用pyflink

**Comment by HuangXingBo** [comment]
pyflink启动会依赖好些shell脚本，windows应该还不能很好的支持这些shell脚本的运行
